In [3]:
import pandas as pd
df= pd.read_csv(r"C:\Users\eshwa\OneDrive\Desktop\customer_shopping_behavior.csv")

In [4]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Yes,31,PayPal,Annually

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3900 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Discount Applied        3900 non-null   str
 13  Previous Purchases      3900 non-null   int64
 14  Payment Method          3900 non-null   str
 15  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(11)
memory usage: 487.6 KB

In [6]:
type(df)

pandas.DataFrame

In [7]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900.000000,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.749949,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716223,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.700000,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,50.000000,NaN,NaN

In [8]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Discount Applied          0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [9]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_') 
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [10]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'discount_applied',
       'previous_purchases', 'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [11]:
#FE = create a column age_group
labels = ['Young Adult','Adult','Middle-aged','Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [12]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [13]:
# create column purchase_frequency_days

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [14]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [15]:
df[['discount_applied']].head(10)

  discount_applied
0              Yes
1              Yes
2              Yes
3              Yes
4              Yes
5              Yes
6              Yes
7              Yes
8              Yes
9              Yes

In [16]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [17]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (2.0.49)
Requirement already satisfied: pymysql in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (1.1.2)
Requirement already satisfied: greenlet>=1 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from sqlalchemy) (4.15.0)

In [18]:
import mysql.connector

In [19]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (9.6.0)

In [20]:
import pandas as pd
from sqlalchemy import create_engine
#Step 1: Connect to MySQL

#Replace placeholders with your actual details
username = "root"    #default user
password = "Ishu@2004#"    #the password you set during installation
host = "localhost"        #if running locally
port = "5432"     #default MySQL port
database = "customer_behavior" #the database you created in MySQL

engine = create_engine(f"postgresql+psycop2://{username}:{password}@{host}:{port}/{database}")

#Step 2: Load DataFrame into MySQL
table_name = "customer" # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgresql.psycop2

In [21]:
!pip install cryptography

Requirement already satisfied: cryptography in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (46.0.7)
Requirement already satisfied: cffi>=2.0.0 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from cryptography) (2.0.0)
Requirement already satisfied: pycparser in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from cffi>=2.0.0->cryptography) (3.0)

In [22]:
pip install --upgrade mysql-connector-python

Requirement already satisfied: mysql-connector-python in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (9.6.0)
Note: you may need to restart the kernel to use updated packages.

In [23]:
!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in .\AppData\Local\Programs\Python\Python311\Lib\site-packages (from sqlalchemy) (4.15.0)

In [26]:
import pandas as pd
from sqlalchemy import create_engine
#Step 1: Connect to MySQL

#Replace placeholders with your actual details
username = "root"    #default user
password = "111"    #the password you set during installation
host = "localhost"        #if running locally
port = "3306"     #default MySQL port
database = "mydatabase" #the database you created in MySQL

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

#Step 2: Load DataFrame into MySQL
table_name = "mytable" # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

#Read back sample
pd.read_sql("SELECT * FROM mytable LIMIT 5;", engine)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Yes,31,PayPal,Annually,Middle-aged,365